---
run:
  # The default concurrency value is the number of available CPU.
  concurrency: 4

  # Timeout for analysis, e.g. 30s, 5m.
  timeout: 3m

  # Exit code when at least one issue was found.
  issues-exit-code: 1

  # If set we pass it to "go list -mod={option}". From "go help modules":
  # If invoked with -mod=readonly, the go command is disallowed from the implicit
  # automatic updating of go.mod described above. Instead, it fails when any changes
  # to go.mod are needed. This setting is most useful to check that go.mod does
  # not need updates, such as in a continuous integration and testing system.
  modules-download-mode: readonly

output:
  # The formats used to render issues.
  # Formats:
  # - `colored-line-number`
  # - `line-number`
  # - `json`
  # - `colored-tab`
  # - `tab`
  # - `html`
  # - `checkstyle`
  # - `code-climate`
  # - `junit-xml`
  # - `junit-xml-extended`
  # - `github-actions`
  # - `teamcity`
  # - `sarif`
  # Output path can be either `stdout`, `stderr` or path to the file to write to.
  #
  # For the CLI flag (`--out-format`), multiple formats can be specified by separating them by comma.
  # The output can be specified for each of them by separating format name and path by colon symbol.
  # Example: "--out-format=checkstyle:report.xml,json:stdout,colored-line-number"
  # The CLI flag (`--out-format`) override the configuration file.
  #
  # Default:
  #   formats:
  #     - format: colored-line-number
  #       path: stdout
  formats:
    - format: colored-line-number
      path: stderr

  # Show statistics per linter.
  # Default: false
  show-stats: true

linters:
  # Start by disabling all linters.
  disable-all: true

  # Enable linters by name (in addition to default).
  enable:
    - protogetter
    - bodyclose
    - depguard
    - errcheck
    - errorlint
    - exhaustruct
    - forbidigo
    - gocritic
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  decorder:
    # Required order of `type`, `const`, `var` and `func` declarations inside a file.
    dec-order:
      - type
      - const
      - var
      - func

    # If true, order of declarations is not checked at all.
    disable-dec-order-check: false

    # If true, `init` func can be anywhere in file (does not have to be declared before all other functions).
    disable-init-func-first-check: false

    # If true, multiple global `type`, `const` and `var` declarations are allowed.
    disable-dec-num-check: false

  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    # Such cases aren't reported by default.
    check-type-assertions: true

    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
    # Such cases aren't reported by default.
    check-blank: true

    # To disable the errcheck built-in exclude list.
    # See `-excludeonly` option in https://github.com/kisielk/errcheck#excluding-functions for details.
    disable-default-exclusions: false

  errorlint:
    # Check whether fmt.Errorf uses the %w verb for formatting errors.
    # See the https://github.com/polyfloyd/go-errorlint for caveats.
    errorf: true

    # Permit more than 1 %w verb, valid per Go 1.20 (Requires errorf:true)
    # Default: true
    errorf-multi: true

    # Check for plain type assertions and type switches.
    asserts: true

    # Check for plain error comparisons.
    comparison: true

  exhaustruct:
    exclude:
      # std libs
      - "^net/http.*"
      - "^database/sql.*"
      # public libs
      - "^golang.org/x/exp/slog"
      - "^github.com/labstack/echo/v4/middleware.*"
      - "^github.com/labstack/echo-jwt/v4.*"
      - "^github.com/MicahParks/keyfunc/v2.*"
      - "^github.com/aws/aws-sdk-go-v2/service/s3.*"
      # any mocks
      - ".*mocks.*"
      - ".*mock.*"

  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US
    ignore-words:
      - cancelled

  nolintlint:
    # Disable to ensure that all nolint directives actually have an effect.
    allow-unused: false

    # Exclude following linters from requiring an explanation.
    # Default: []
    allow-no-explanation: []

    # Enable to require an explanation of nonzero length after each nolint directive.
    require-explanation: true

    # Enable to require nolint directives to mention the specific linter being suppressed.
    require-specific: true

  gosec:
    # To select a subset of rules to exclude.
    # Available rules: https://github.com/securego/gosec#available-rules
    excludes:
      - G107 # Dynamic URL for HTTP request
      - G404 # Allow use of math/rand
      - G115 # Many cases of casting from float64 to int32 and none of them are going to truncate

  stylecheck:
    # STxxxx checks in https://staticcheck.io/docs/configuration/options/#checks
    checks: ["all", "-ST1003"]

  govet:
    disable:
      # Disabled to allow autogen types from sqlc
      - composites

  staticcheck:
    # STxxxx checks in https://staticcheck.io/docs/configuration/options/#checks
    checks: ["all", "-SA1029"]

  depguard:
    rules:
      # Name of a rule.
      main:
        # Packages that are not allowed where the value is a suggestion.
        deny:
          - pkg: "golang.org/x/exp/slog"
            desc: "Please use log/slog instead"
          - pkg: "github.com/bufbuild/connect-go"
            desc: "Please use connectrpc.com/connect instead"
          - pkg: "github.com/pingcap/log"
            desc: "Please use log/slog instead of this"
          - pkg: "github.com/pkg/errors"
            desc: "The stdlib errors package should have all you need now"
          - pkg: "golang.org/x/exp/slices"
            desc: "Please use slices from the stdlib"
          - pkg: "github.com/stretchr/testify/assert"
            desc: "Please use testify/require instead"

issues:
  # Make issues output unique by line.
  uniq-by-line: false

  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0
  exclude-dirs:
    - generated/proto
    - internal/datastores/generated
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - exhaustruct
