tap 'git-duet/tap'
tap 'ryanmoran/tools'

brew 'bash'
brew 'bash-completion'
brew 'coreutils'
brew 'gh'
brew 'git'
brew 'git-duet/tap/git-duet'
brew 'go'
brew 'graphviz'
brew 'htop'
brew 'jq'
brew 'neovim'
brew 'node'
brew 'rustup'
brew 'ryanmoran/tools/faux'
brew 'shellcheck'
brew 'the_silver_searcher'
brew 'tree'
brew 'watch'
brew 'wget'

cask 'docker'
cask 'firefox'
cask 'flycut'
cask 'iterm2'
cask 'rectangle'
