tap 'homebrew/cask'
tap 'ryanmoran/tools'

brew 'bash-completion'
brew 'git'
brew 'go'
brew 'graphviz'
brew 'jq'
brew 'neovim'
brew 'nodejs'
brew 'python3'
brew 'ryanmoran/tools/faux'
brew 'shellcheck'
brew 'sqlite'
brew 'the_silver_searcher'
brew 'watch'
brew 'wget'
brew 'yq'

cask '1password'
cask 'docker'
cask 'dropbox'
cask 'encryptme'
cask 'firefox'
cask 'flycut'
cask 'google-chrome'
cask 'iterm2'
cask 'spectacle'
